// Generated by CoffeeScript 2.7.0
module.exports = async function({config}) {
  var $status;
  await this.log.cli();
  ({$status} = (await this.lxc.cluster(config)));
  console.info(`Cluster was created: ${$status}`);
};
