// Generated by CoffeeScript 2.7.0
var fetch;

fetch = require("node-fetch-commonjs");

module.exports = async function({
    config,
    tools: {log}
  }) {
  var auth, cookies, crumb, crumbRequestField, ref, ref1, response;
  if (!config.address) {
    throw Error("Missing address");
  }
  if (!config.route) {
    throw Error("Missing route");
  }
  auth = `${config.username}:${config.password}`;
  auth = Buffer.from(auth).toString("base64");
  response = (await fetch(`${config.address}/crumbIssuer/api/json`, {
    // credentials: "include"
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: "Basic " + auth
    }
  }));
  cookies = response.headers.get("set-cookie");
  ({crumbRequestField, crumb} = (await response.json()));
  log({
    message: `Send request to ${config.address}/${config.route}`,
    level: "DEBUG"
  });
  response = (await fetch(`${config.address}/${config.route}`, {
    credentials: "include",
    method: (ref = config.method) != null ? ref : "GET",
    headers: {
      Accept: "application/json",
      "Content-Type": (ref1 = config.contentType) != null ? ref1 : "application/json",
      Authorization: "Basic " + auth,
      cookie: cookies,
      [`${crumbRequestField}`]: crumb
    },
    body: config.body
  }));
  return response.text();
};
