// Generated by CoffeeScript 2.7.0
module.exports = async function({config}) {
  await this.ssh.open({
    $header: "Open SSH connection"
  }, config.ssh);
  await this.jenkins.user(config);
  await this.jenkins.install(config);
  await this.jenkins.config(config);
  await this.jenkins.start();
  await this.jenkins.installPlugins(config);
  await this.ssh.close({
    $header: "Closing SSH connection"
  });
};
