// Generated by CoffeeScript 2.7.0
module.exports = async function({config}) {
  await this.system.group({
    $header: "Create Jenkins group",
    gid: config.jenkins_user.gid,
    name: config.jenkins_user.name,
    system: true
  });
  await this.system.user({
    $header: "Create Jenkins service account",
    comment: "Jenkins service account",
    gid: config.jenkins_user.gid,
    home: config.jenkins_user.home,
    name: config.jenkins_user.name,
    system: true,
    uid: config.jenkins_user.uid
  });
};
